### ISSUE TITLE
Time Zone mismatch between tooltip and chart

### ISSUE THREAD

**Issue by gstroup** [PredixDev/px-vis-timeseries#32] opened 2016-12-15 18:40 UTC
## Expected behavior and actual behavior:
Out of the box, I would expect the time zone displayed in the tooltip to match the timezone on the chart.  It does not.  It appears to be off by about 7 hours for me, in Pacific time zone.  Perhaps GMT vs PST?  Not sure.

## Steps to reproduce the problem:
View the component on predix-ui.com:  https://www.predix-ui.com/?show=px-vis-timeseries&type=component
Hover over the graph.  (See attached image.)

## Screenshots (_optional, but very helpful_):

![screen shot 2016-12-15 at 10 32 33 am](https://cloud.githubusercontent.com/assets/431334/21236969/ef1caaba-c2b1-11e6-894c-dcc9457e2801.png)

**Comment by nonmetalhail** [comment] 2016-12-15 18:44
This is a known issue and will be resolved in the next major release. 

Please see https://github.com/PredixDev/px-vis-timeseries/issues/26 for a fix in the meantime.

**Comment by gstroup** [comment] 2016-12-15 18:55
Thanks!  (I didn't see #26 since it was marked as "closed".)

**Comment by sachinbhopi92** [comment] 2016-12-16 08:59
Is this issue resolved yet?

**Comment by benoitjchevalier** [comment] 2016-12-16 16:40
As mentioned above it will be fixed in the next major version (on its way) and a fix is described in #26 in the meantime

**Comment by nonmetalhail** [comment] 2017-03-13 17:58
v1.0 released and resolves this

**Closed by nonmetalhail** 2017-03-13 17:58 UTC

**Comment by VI-GE** [comment] 2017-05-05 12:53
Hello,

I am using version 1.1 and this issue still exists, the tooltip used GMT.

Furthermore I've glanced at the code and the xAxisType is never passed to the tooltip so I don't know how this is supposed to work, maybe I am missing something.

In my case setting the timezone in the tooltip-config didn't work either and unfortunately there isn't any documentation on this either, I was forced to look into the source code to figure some things out.

**Comment by benoitjchevalier** [comment] 2017-05-05 16:20
Hello,

is your issue that the tooltip time doesn't seem to match the time on the axis or just that it seems to use a timezone different than you expect? Can you elaborate? I want to make sure I understand your issue properly and that we all talk about the same thing.

Regarding the API every `something-config` options can be found in the API of the appropriate `something` element on the vis framework documentation: https://www.predix-ui.com/#/components/px-vis/ . In this case you can use any of the tooltip API in `tooltip-config`

**Comment by VI-GE** [comment] 2017-05-09 08:00
Hello,

Yes the issue is that The tooltip time does not match the chart time even if I pass xAxisType = 'timeLocal' to the component.

I have glanced in the source and it seems to me that there are no parameters related to the time that are passed to the tooltip component.

Also the workaround of setting the timezone  mentioned here : #26 didn't work for me.

Thank you

**Comment by nonmetalhail** [comment] 2017-05-09 15:18
The tooltip is not an axis and as such, xAxisType has no effect on it. You'll find the parameters to configure time on the tooltip If you read the docs frenchben posted.

**Comment by VI-GE** [comment] 2017-05-09 15:23
@nonmetalhail I have tried to configure the timezone via tooltip-config as mentioned by Benoit but it didn't work, I will have to analyze why, perhaps it's related to me creating the charts dynamically and configuring them via properties instead, but timeLocal and other options work that way so I don't know.
I'll research this further.

In that case I don't understand what was fixed in 1.0 since this issue has been closed and it mentions the 1.0 release as resolving this.

**Comment by nonmetalhail** [comment] 2017-05-09 15:35
The fix want standardizing the axis on utc; previously, the axis displayed local and the tooltip utc.

Please submit a codepen of what you've tried so we can take a look

**Comment by VI-GE** [comment] 2017-05-10 08:33
@nonmetalhail After more analysis  and looking at the demo I have realised I wasn't actually talking about the tooltip but the toolbar (it shows part of the same information as the tooltip there, on the default config). Sorry about that.

Unfortunately the docs state that for the available tooltipConfig properties you should check the px-vis github page and there I can't find any documentation.

Is it possible to set the toolbar date to be in the same timezone as the bottom date on the chart?

Thank you

**Comment by nonmetalhail** [comment] 2017-05-10 18:29
I think you are confusing the toolbar and the register. The toolbar is a series of buttons on the chart, by default controlling the zoom and panning. The register shows the timestamp and series values. If this is what you want to configure, then you should pass the properties through the registerConfig property. The available configuration options for customizing the date are the same as for the tooltip.

**Comment by benoitjchevalier** [comment] 2017-05-10 18:45
Yes, you probably want to look at `timezone` on `registerConfig` and possibly `firstDateTimeFormat`

**Comment by VI-GE** [comment] 2017-05-11 09:18
Thank you @benoitjchevalier and @nonmetalhail That was what I needed.

I find it still kinda strange that you need different configs to synchronise the times like that, I'd have expected them to share the configuration passed on the vis-timeseries.

Anyway thanks again for your help.
